- name: install basic packaging tools
  become: true
  package:
    name: "{{ packaging_packages | join(',') }}"
    state: present

- name: setup user for mock
  become: true
  user:
    name: "{{ mock_user }}"
    groups: mock
    append: true
  tags:
    - config
