- name: install basic packaging tools
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - fedpkg
    - fedora-packager
    - fedora-review
    - mock
    - fedrepo-req

- name: setup user for mock
  become: true
  user:
    name: "{{ mock_user }}"
    groups: mock
    append: true
  tags:
    - config
