- name: install basic packaging tools
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - fedpkg
    - fedora-packager
    - fedora-review
    - mock

- name: setup user for mock
  become: true
  user:
    name: vagrant
    groups: mock
    append: true
