Vagrant.configure("2") do |config|
    vm(config, "webserver", "centos/7") do |node|
        ansible(node, '../../mkgreg/site.yml') do |ansible|
            ansible.groups = {
                'webserver:vars' => {
                    'webserver_domains' => [{
                        'tld' => '__derp.com',
                        'https' => false
                    }].to_json
                }
            }
        end
    end
end
