- name: configure for cinch development
  hosts: cinch
  roles:
    - cinch

- name: configure for linch-pin development
  hosts: linch-pin
  roles:
    - linch_pin

- name: basic user config files
  hosts: all
  roles:
    - vimrc
    - bashrc
