- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - acd_cli # Amazon Cloud Drive
    # These two are dependencies of acd_cli that are missing from the packaging
    - python3-dateutil
    - python3-fuse
    - google-drive-ocamlfuse
