- name: install repositories
  become: true
  yum_repository:
    description: A repository
    name: "{{ item.name }}"
    baseurl: "{{ item.url | default(omit) }}"
    mirrorlist: "{{ item.mirrors | default(omit) }}"
    enabled: true
    gpgcheck: "{{ item.gpgcheck | default(false) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    skip_if_unavailable: "{{ item.skip | default(true) }}"
  with_items: "{{ gui_repositories }}"

- name: install necessary GUI packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - https://spideroak.com/release/spideroak/rpm_x64
    - SpiderOak
    - vim-X11
    - google-chrome-stable
    - gnome-tweak-tool
    - gnome-shell-extension-*
    - xchat
    - polkit-gnome
    - shutter
    - virt-manager
    - HandBrake-gui
    - intellij-idea-community
    #- pycharm-community
    - vlc
    - entropypianotuner
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - http://hdn.corp.redhat.com/rhel7-csb-stage/RPMS/noarch/redhat-internal-cert-install-0.1-7.el7.csb.noarch.rpm
    - http://hdn.corp.redhat.com/rhel7-csb-stage/RPMS/noarch/redhat-internal-NetworkManager-openvpn-profiles-0.1-29.el7.csb.noarch.rpm
