- name: configure storage volume for Docker
  become: true
  filesystem:
    dev: "{{ docker_storage_volume }}"
    fstype: "{{ docker_block_filesystem_type }}"

- name: install necessary packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - git

- name: ensure the docker storage volume is a mountpoint
  become: true
  lineinfile:
    dest: /etc/fstab
    line: "{{ docker_storage_volume}}    /var/lib/docker    ext4    defaults 0 0"

- name: mount docker storage
  become: true
  mount:
    name: /var/lib/docker
    state: mounted
    src: "{{ docker_storage_volume }}"
    fstype: "{{ docker_block_filesystem_type }}"

- name: set docker to use overlay2
  become: true
  template:
    src: docker-storage-setup
    dest: /etc/sysconfig/docker-storage-setup
    mode: 0644
    owner: root
  register: storage_setup

- name: run docker storage
  become: true
  shell: docker-storage-setup
  when: storage_setup | changed
