- name: install repositories
  become: true
  yum_repository:
    description: A repository
    name: "{{ item.name }}"
    baseurl: "{{ item.url | default(omit) }}"
    mirrorlist: "{{ item.mirrors | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    enabled: "{{ item.enabled | default(true) }}"
    gpgcheck: "{{ item.gpgcheck | default(false) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    skip_if_unavailable: "{{ item.skip | default(true) }}"
    exclude: "{{ item.exclude | default(omit) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
  with_items: "{{ repositories }}"
  tags:
    - config
