- name: link to bash files
  file:
    src: "{{ playbook_dir }}/roles/bashrc/files/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    state: link
    force: true
  with_items: "{{ bashrc_files }}"

- name: link to helper files
  file:
    src: "{{ playbook_dir }}/roles/bashrc/files/local/bin"
    dest: "{{ ansible_user_dir }}/.local/bin"
    state: link
    force: true
