- name: install CLI packages
  become: true
  package:
    name: "{{ cli_packages }}"
    state: present

- name: remove packages that shouldn't hang around
  become: true
  package:
    name: "{{ cli_remove_packages }}"
    state: absent

- name: install dnf tools
  become: true
  package:
    name: "{{ cli_dnf_packages }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'
