- name: install Kerberos
  become: true
  package:
    name:
      - krb5-libs
      - krb5-workstation
    state: present

- name: configure Kerberos
  become: true
  template:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    mode: 0644
