- name: install Vagrant
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - vagrant-sshfs
    - vagrant-cachier
    - vagrant-libvirt

- name: discover ruby version
  shell: "ruby --version | cut -d' ' -f 1 | sed -e 's/p.*$//'"
  changed_when: false
  register: ruby_version

# TODO: Figure out how to detect ruby version in order to specify the
# correct value of the creates= argument to this command
- name: install Vagrant openstack
  command: vagrant plugin install vagrant-openstack-provider
  args:
    creates: "{{ ansible_user_dir }}/.vagrant.d/gems/{{ ruby_version.stdout }}/gems/vagrant-openstack-provider-0.11.0/"
  changed_when: false
