- name: create python virtualenvs
  pip:
    virtualenv: "{{ ansible_user_dir }}/venv/{{ item.name }}"
    state: present
    name: "{{ item.packages }}"
    virtualenv_python: "{{ item.python }}"
  with_items:
    - name: tools2
      packages: &packages
        - wheel
        - ipython
        - Pygments
        - cookiecutter
        - ansible
        - molecule
        - openstacksdk
        - docker
        - twine
        - dnf
      python: python2
    - name: tools3
      packages: *packages
      python: python3
  retries: 3
  register: create_virtualenvs
  until: create_virtualenvs is success
