- name: basic user config files
  hosts: all
  roles:
    - devroles.system.authorized_key
    - devroles.system.bashrc
    - devroles.system.vimrc
    - role: devroles.system.copy_or_link
      copy_or_link_files: "{{ private_files | default([]) }}"
    - devroles.system.gitconfig
  tags:
    - config
