- name: ensure vim directory is created
  file:
    dest: "{{ item }}"
    state: directory
    force: true
  with_items:
    - "{{ ansible_user_dir }}/.vim"
    - "{{ ansible_user_dir }}/.vim/autoload"
    - "{{ ansible_user_dir }}/.vim/bundle"
    - "{{ ansible_user_dir }}/.vim/sessions"

- name: install static files (remote)
  include: remote.yml
  when: ansible_connection != 'local'

- name: install static files (local)
  include: local.yml
  when: ansible_connection == 'local'

- name: download pathogen
  get_url:
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: "{{ ansible_user_dir }}/.vim/autoload"
    force: true

- name: checkout vim plugins
  git:
    dest: "{{ ansible_user_dir }}/.vim/bundle/{{ item.name }}"
    repo: "{{ item.repo }}"
    update: true
  with_items:
    - repo: https://github.com/jlanzarotta/bufexplorer.git
      name: bufexplorer
    - repo: https://github.com/ctrlpvim/ctrlp.vim.git
      name: ctrlp
    - repo: https://github.com/scrooloose/nerdtree.git
      name: nerdtree
    - repo: https://github.com/pangloss/vim-javascript.git
      name: vim-javascript
    - repo: https://github.com/airblade/vim-gitgutter.git
      name: vim-gitgutter
    - repo: https://github.com/nvie/vim-flake8.git
      name: vim-flake8
    - repo: https://github.com/tpope/vim-fugitive.git
      name: vim-fugitive
    - repo: https://github.com/nathanaelkane/vim-indent-guides.git
      name: vim-indent-guides
    - repo: https://github.com/morhetz/gruvbox.git
      name: gruvbox
