- name: update selected packages
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim-minimal

- name: install shared tools
  become: true
  package:
    name: "{{ common_packages | join(',') }}"
    state: present

- name: disable selinux
  become: true
  selinux: state=disabled

- name: enable SSHD
  become: true
  service:
    name: sshd
    state: started
    enabled: true
  when: ansible_os_family != 'Darwin'
