libvirt_storage: /home/libvirt
gui: true
gui_repositories:
  - name: google-chrome
    url: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    gpgcheck: true
  - name: copr-phracek-PyCharm
    url: https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/fedora-$releasever-$basearch/
    gpgcheck: true
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/pubkey.gpg
  - name: copr-rommon-intellij-idea
    url: https://copr-be.cloud.fedoraproject.org/results/rommon/intellij-idea/fedora-$releasever-$basearch/
    gpgcheck: true
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/rommon/intellij-idea/pubkey.gpg
  - name: entropypianotuner
    url: http://download.opensuse.org/repositories/home:/entropytuner/Fedora_$releasever/
    gpgkey: http://download.opensuse.org/repositories/home:/entropytuner/Fedora_$releasever/repodata/repomd.xml.key
cli_repositories:
  - name: fedora-Handbrake
    url: http://negativo17.org/repos/HandBrake/fedora-$releasever/$basearch/
    gpgcheck: true
    gpgkey: http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
  - name: fedora-Handbrake-source
    url: http://negativo17.org/repos/HandBrake/fedora-$releasever/SRPMS/
    gpgcheck: true
    gpgkey: http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
  - name: google-cloud-ocamlfuse
    url: https://copr-be.cloud.fedoraproject.org/results/sergiomb/google-drive-ocamlfuse/fedora-$releasever-$basearch/
    gpgcheck: true
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/regiomb/google-drive-ocamlfuse/pubkey.gpg
