require '../shared.rb'

etcd_hosts = '[{ "host" : "192.168.8.2", "port" : 2379 }]'
Vagrant.configure('2') do |config|
    vm(config, 'support', 'centos/7')
    vm(config, 'master', 'centos/7')
    vm(config, 'slave', 'centos/7') do |vm|
        ansible(vm) do |ansible|
            ansible.groups = {
                "kubernetes_master" => ["master"],
                "kubernetes_slave" => ["master", "slave"],
                "etcd" => ["support"],
                "kubernetes_master:vars" => {
                    "etcd_hosts"=> etcd_hosts,
                    "kubernetes_private_ip" => "192.168.8.3"
                },
                "kubernetes_slave:vars" => {
                    "master_url"=> "http://192.168.8.3:8080",
                    "etcd_hosts"=> etcd_hosts,
                    "kubernetes_private_ip" => "192.168.8.4"
                }
            }
        end
    end
end
