- name: install kubernetes basics
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubernetes
    - etcd
    - flannel

- name: construct etcd_urls
  set_fact:
    _etcd_urls: "{{ (_etcd_urls | default([]) ) + ['http://' + item['host'] + ':' ~ item['port'] ] }}"
  with_items: "{{ etcd_hosts }}"

- name: drop in kubernetes config
  become: true
  template:
    src: kubernetes_config.j2
    dest: /etc/kubernetes/config
    owner: root
    mode: 0644

- name: stop firewalld
  become: true
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - firewalld

- name: configure flanneld
  become: true
  template:
    src: flanneld.j2
    dest: /etc/sysconfig/flanneld
    owner: root
    mode: 0644
  notify: restart flanneld
