- name: install etcd
  package:
    name: etcd
    state: present

- name: install etcd config file
  template:
    src: etcd.conf
    dest: /etc/etcd/etcd.conf
    owner: root
    mode: 0644
  notify: restart etcd

- name: start and enable etcd
  service:
    name: etcd
    state: started
    enabled: true

- name: initialize etcd hosts list
  set_fact:
    etcd_hosts: []
    etcd_url: "{{ etcd_url }}"
    etcd_port: "{{ etcd_port }}"

- name: construct etcd hosts list
  set_fact:
    etcd_hosts: "{{ etcd_hosts + [hostvars[item]['etcd_url']] }}"
  with_items: "{{ groups['etcd'] }}"
