- name: install etcd
  become: true
  package:
    name: etcd
    state: present

- name: install etcd config file
  become: true
  template:
    src: etcd.conf
    dest: /etc/etcd/etcd.conf
    owner: root
    mode: 0644
  notify: restart etcd

- name: start and enable etcd
  become: true
  service:
    name: etcd
    state: started
    enabled: true
