gui_repositories:
  - name: bluejeans
    baseurl: https://swdl.bluejeans.com/repos/bluejeans/x86_64/release/rpm
    gpgcheck: true
    gpgkey: https://swdl.bluejeans.com/repos/bluejeans/bjn-key
    description: bluejeans
  - name: entropypianotuner
    baseurl: https://copr-be.cloud.fedoraproject.org/results/greghellings/EntropyPianoTuner/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/greghellings/EntropyPianoTuner/pubkey.gpg
    gpgcheck: true
    description: Greg Hellings' builds of Entropy Piano Tuner
  - name: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    gpgcheck: true
    description: Google Chrome
  - name: google-talkplugin
    baseurl: http://dl.google.com/linux/talkplugin/rpm/stable/x86_64/
    gpgcheck: true
    description: Google Talk Plugin
gui_packages:
  - /tmp/spideroak.rpm
  - vim-X11
  - google-chrome-stable
  - gnome-tweak-tool
  - gnome-shell-extension-*
  - hexchat
  - polkit-gnome
  - shutter
  - virt-manager
  - HandBrake-gui
  - transmission
  - vlc
  - entropypianotuner
  - NetworkManager-openvpn
  - NetworkManager-openvpn-gnome
  - avidemux-gui
  - openshot
  - qwinff
  - sound-juicer
