repositories:
  - name: bluejeans
    url: https://swdl.bluejeans.com/repos/bluejeans/x86_64/release/rpm
    gpgcheck: true
    gpgkey: https://swdl.bluejeans.com/repos/bluejeans/bjn-key
  - name: entropypianotuner
    url: https://copr-be.cloud.fedoraproject.org/results/greghellings/EntropyPianoTuner/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/greghellings/EntropyPianoTuner/pubkey.gpg
    gpgcheck: true
  - name: google-chrome
    url: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    gpgcheck: true
  - name: google-talkplugin
    url: http://dl.google.com/linux/talkplugin/rpm/stable/x86_64/
    gpgcheck: true
packages:
  - /tmp/spideroak.rpm
  - vim-X11
  - google-chrome-stable
  - gnome-tweak-tool
  - gnome-shell-extension-*
  - hexchat
  - polkit-gnome
  - shutter
  - virt-manager
  - HandBrake-gui
  - transmission
  - vlc
  - entropypianotuner
  - NetworkManager-openvpn
  - NetworkManager-openvpn-gnome
  - avidemux-gui
