- name: install kubernetes client
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubernetes-client

- name: create .kube directory
  file:
    dest: "{{ ansible_user_dir }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"

- name: install .kube/config
  template:
    src: dotkube_config.j2
    dest: "{{ ansible_user_dir }}/.kube/config"
    owner: "{{ ansible_user }}"
