- name: ensure target exists
  file:
    dest: "{{ item.target }}"
    state: directory

- name: ensure mountpoint exists
  mount:
    state: present
    fstype: "{{ item.fstype }}"
    name: "{{ item.target }}"
    src: "{{ item.device }}"

- name: mount item
  mount:
    state: mounted
    fstype: "{{ item.fstype }}"
    name: "{{ item.target }}"
    src: "{{ item.device }}"