- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kernel-devel
    - akmod-nvidia
    - libdvdcss
    - mythtv

- name: fetch Hauppage 950 firmware
  get_url:
    dest: "{{ ansible_user_dir }}/HVR-950.zip"
    url: "http://www.steventoth.net/linux/xc5000/HVR-12x0-14x0-17x0_1_25_25271_WHQL.zip"
    force: true
  notify: extract Hauppage firmware

- name: start and enable MariaDB
  become: true
  service:
    name: mariadb
    state: started
    enabled: true

- name: import mythtv schema
  command: mysql < /usr/share/doc/mythtv-docs/database/mc.sql
  args:
    creates: /var/lib/mysql/mythconverg

- name: grant mythtv user privileges
  mysql_user:
    name: mythtv
    host_all: true
    priv: "mythconverg.*:ALL"
    state: present
