- name: installing swordweb deps
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - omniORB-devel
    - java-1.8.0-openjdk-headless
    - java-1.8.0-openjdk-devel
