- name: install necessary files
  become: true
  package:
    name: "{{ java_devel_packages | join(',') }}"

- name: ensure m2 directory exists
  file:
    dest: "{{ ansible_user_dir }}/.m2/"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755

- name: configure maven repository
  template:
    src: settings.xml
    dest: "{{ ansible_user_dir }}/.m2/settings.xml"
    owner: "{{ ansible_user }}"
    mode: 0644
