# -*- mode: ruby -*-
# vi: set ft=ruby :

def get_username(base_box)
	if base_box.start_with?('centos')
		return 'centos'
	elsif base_box.start_with?('rhel')
		return 'root'
	else
		return 'fedora'
	end
end

def get_image(base_box)
	if base_box == 'centos/7'
		return 'CentOS-7-x86_64-GenericCloud-released-latest'
	elsif base_box == 'centos/6'
		return 'CentOS-6-x86_64-GenericCloud-released-latest'
	elsif base_box == 'fedora/25-cloud-base'
		return 'Fedora-Cloud-Base-25-compose-latest'
	elsif base_box == 'fedora/24-cloud-base'
		return 'Fedora-Cloud-Base-24-compose-latest'
	elsif base_box == 'fedora/27-cloud-base'
		return 'Fedora-Cloud-Base-27-1.6'
	end
end

Vagrant.configure("2") do |config|
	config.vm.provider :openstack do |os, override|
		os.openstack_auth_url = ENV['OS_AUTH_URL']
		os.username = ENV['OS_USERNAME']
		os.password = ENV['OS_PASSWORD']
		os.tenant_name = ENV['OS_PROJECT_NAME']
		os.flavor = ENV['OS_NOVA_FLAVOR']
		os.floating_ip_pool = ENV['OS_FLOATING_NETWORK']
		os.networks = [{ name: ENV['OS_NETWORK'] }]
		os.server_create_timeout = 900
	end
end
