require '../shared.rb'

Vagrant.configure('2') do |config|
    vm(config, 'packaging', 'greg-hellings/fedora-26-alpha') do |node|
        node.vm.provision :shell, inline: "dnf install -y python"
        ansible(node)
        node.vm.provider :libvirt do |virt|
            virt.memory = 2048
            virt.cpus = 2
        end
    end
end
