- name: install dependency packages
  become: true
  package:
    name: "{{ cinch_packages | join(',') }}"
    state: present

- name: install extra python dev packages
  pip:
    virtualenv: "{{ ansible_user_dir }}/venv/cinch"
    name: "{{ item }}"
    state: present
  with_items:
    - ipython

- name: install released versions to new virtualenvs
  pip:
    virtualenv: "{{ ansible_user_dir }}/venv/{{ item }}"
    name: cinch=={{ item }} ipython
    state: present
  with_items:
    - 0.2.1
    - 0.3.0
    - 0.4.1
    - 0.5.1
    - 0.6.0
    - 0.7.0
    - 0.8.0
    - 0.9.0

- name: start and enable docker
  become: true
  service:
    name: docker
    state: started
    enabled: true

- name: check out code
  git:
    repo: https://github.com/RedHatQE/cinch
    dest: "{{ ansible_user_dir }}/cinch"
