- name: install python2-dnf
  become: true
  shell: dnf install -y python2-dnf creates=/usr/lib/python2.7/site-packages/dnf
  when: ansible_distribution == 'Fedora'

- name: update selected packages
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim-minimal

- name: install shared tools
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - gcc-c++
    - git
    - redhat-rpm-config
    - libselinux-python
    - mlocate
    - screen
    - patch

- name: disable selinux
  become: true
  selinux: state=disabled
  when: "'OSEv3' not in groups"

- name: enable SSHD
  become: true
  service:
    name: sshd
    state: started
    enabled: true
  when: ansible_os_family != 'Darwin'
