dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: gui
    image: fedora:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
verifier:
  name: testinfra
  lint:
    name: flake8
  directory: ../shared/
