- name: install etcd python help
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-urllib3
    - "https://kojipkgs.fedoraproject.org//packages/python-etcd/0.4.3/1.fc24/noarch/python2-python-etcd-0.4.3-1.fc24.noarch.rpm"
    - python-requests

- name: configure network in etcd
  run_once: true
  etcd:
    state: present
    key: "{{ item.key }}"
    value: "{{ item.value | to_json }}"
    host: "{{ etcd_hosts[0]['host'] }}"
    port: "{{ etcd_hosts[0]['port'] }}"
  with_items:
    - key: /kube-centos/network/config
      value:
        Network: "{{ kubernetes_network_prefix }}"
        SubnetLen: "{{ kubernetes_network_prefix_length }}"
        Backend:
          # We'd like this to be 'vxlan' but that requires kernel 3.14+
          Type: udp

- name: configure kubernetes apiserver
  become: true
  template:
    src: kubernetes_apiserver.j2
    dest: /etc/kubernetes/apiserver
    owner: root
    mode: 0644
  notify: restart kubernetes

- name: set ownership of kubernetes files
  become: true
  file:
    dest: /var/run/kubernetes
    owner: kube
    recurse: true
    state: directory

- name: start and enable services
  become: true
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - flanneld

- name: export variables
  set_fact:
    kubernetes_server_port: "{{ kubernetes_server_port }}"
    kubernetes_private_ip: "{{ kubernetes_private_ip }}"
