- name: install necessary rpms
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - krb5-workstation
    - make
  become: true

- name: install virtualenv
  pip:
    virtualenv: "{{ ansible_user_dir }}/venv/linchpin"
    state: present
    name: "{{ item }}"
    virtualenv_site_packages: true
  with_items:
    - jsonschema
    - functools32
    - ansible
    - python-krbV
    - ipython

- name: create /etc/beaker
  file:
    dest: /etc/beaker
    owner: "{{ ansible_user }}"
    mode: 0700
    state: directory
  become: true

- name: give temporary write access to bash completions
  file:
    dest: /usr/share/bash-completion/completions/
    mode: a+w
    state: directory
  become: true

- name: install bash_local
  copy:
    src: bash_local
    dest: "{{ ansible_user_dir }}/.bash_local"

- name: check out code
  git:
    dest: "{{ ansible_user_dir }}/linchpin"
    repo: http://github.com/greg-hellings/linch-pin
