- name: install virtualenv
  pip:
    virtualenv: "{{ ansible_user_dir }}/venv"
    state: present
    name: "{{ item }}"
  with_items:
    - jsonschema
    - functools32
    - ansible
    - python-krbV
    - ipython

- name: create /etc/beaker
  become: true
  file:
    dest: /etc/beaker
    owner: "{{ ansible_user }}"
    mode: 0700
    state: directory

- name: give temporary write access to bash completions
  become: true
  file:
    dest: /usr/share/bash-completion/completions/
    mode: a+w
    state: directory

- name: install bash_local
  copy:
    src: bash_local
    dest: "{{ ansible_user_dir }}/.bash_local"
