dev_repositories:
  - name: copr-phracek-PyCharmr
    url: https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/fedora-$releasever-$basearch/
    gpgcheck: true
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/pubkey.gpg
  - name: greghellings-intellij-idea
    url: https://copr-be.cloud.fedoraproject.org/results/greghellings/intellij-idea/fedora-$releasever-$basearch/
    gpgcheck: true
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/greghellings/intellij-idea/pubkey.gpg
dev_packages:
  #- intellij-idea-community
  - pycharm-community
