# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi
PATH=$HOME/.local/bin:$HOME/.local/lib/flex/bin:/opt/android-studio/bin:/opt/intellij/bin:/opt/packer:$PATH


export PATH
export JAVA_HOME
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export SWORD_HOME=$HOME/.sword
