# ############################################################################
# Preliminary stuff that all the hosts need
# ############################################################################
- name: mounts
  hosts: all:!noadmin
  roles:
    - common
    - mounts

- name: prepare for openshift
  hosts: OSEv3
  gather_facts: false
  roles:
    - ose_warmup

# ############################################################################
# Personal desktop configuration, for use on systems that I administrate, and
# where GUI programs are needed
# ############################################################################
- name: configure desktop systems
  hosts: desktop
  roles:
    - desktop

# ############################################################################
# Kubernetes and related configurations
# ############################################################################
#- name: etcd needs to be up before kubernetes
#  hosts: etcd
#  gather_facts: false
#  roles:
#    - etcd

- name: install kubernetes masters to configure system
  hosts: kubernetes_master
  roles:
    - kubernetes-master

- name: configure kubernetes slaves
  hosts: kubernetes_slave
  roles:
    - kubernetes-slave

- name: install kubernetes client configuration
  hosts: kubernetes_master:kubernetes_slave:kubernetes_client
  roles:
    - kubernetes-client

- name: install kubernetes containers and other apps
  hosts: kubernetes_master[0]
  roles:
    - kubernetes-containers
# ############################################################################
# Development machines, designed to be spun up in local VMs
# ############################################################################
- name: configure for cinch development
  hosts: cinch
  gather_facts: false
  roles:
    - docker
    - cinch

- name: configure for linch-pin development
  hosts: linchpin
  gather_facts: false
  roles:
    - linch_pin

- name: configure for Fedora packaging development
  hosts: packaging
  gather_facts: false
  roles:
    - packaging

- name: configure a basic docker system
  hosts: docker
  gather_facts: false
  roles:
    - docker

- name: sword development
  hosts: sword
  gather_facts: false
  roles:
    - docker
    - sword
    - swordweb
# ############################################################################
# Simple user-land configuration that does not require root access to install
# but makes my life so much easier! Designed to be run on any system that I
# have login-level access to
# ############################################################################
- name: basic user config files
  hosts: all
  roles:
    - vimrc
    - bashrc
    - gitconfig
    - private_files
    - cleanup
