- name: install dependency packages
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-devel
    - python-virtualenv
    - libyaml-devel
    - openssl-devel
    - libffi-devel
    - ShellCheck

- name: install extra python dev packages
  pip:
    virtualenv: "{{ ansible_user_dir }}/venv/cinch"
    name: "{{ item }}"
    state: present
  with_items:
    - ipython

- name: copy in bash_local file
  template:
    src: bash_local
    dest: "{{ ansible_user_dir }}/.bash_local"
