- name: install bash configuration (local)
  import_tasks: local.yml
  when: ansible_connection == 'local'

- name: install bash configuration (remote)
  import_tasks: remote.yml
  when: ansible_connection != 'local'

- name: set executable file permissions
  file:
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: a+x
    recurse: true
