- name: set bashrc_role_path
  set_fact:
    bashrc_role_path: "{{ role_path }}"

- name: run files
  include_role:
    name: greg_hellings.copy_or_link
  vars:
    copy_or_link_files: "{{ bashrc_files }}"

- name: set executable file permissions
  file:
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: a+x
    recurse: true
