- name: install Ansible build deps
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python2-virtualenv
    - libffi-devel
    - openssl-devel
    - libyaml-devel
    - gmp-devel
